services:
  api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:latest
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./docker_data/instances:/evolution/instances
      - ./docker_data/redis:/data/redis
      - ./docker_data/postgres:/var/lib/postgresql/data
    networks:
      - shared-net
    env_file:
      - .env
    expose:
      - 8080

  redis:
    image: redis:latest
    networks:
      - shared-net
    container_name: evolution_redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: >
       redis-server --requirepass ${REDIS_PASSWORD} --port 6379 --appendonly yes
    volumes:
      - ./docker_data/redis:/data

  postgres:
    container_name: evolution_postgres
    image: postgres:15
    networks:
      - shared-net
    command: ["postgres", "-c", "max_connections=1000", "-c", "listen_addresses=*"]
    restart: always
    env_file:
      - .env
    volumes:
      - ./docker_data/postgres:/var/lib/postgresql/data
    ports:
      - 5434:5432
    expose:
      - 5434

networks:
  shared-net:
    name: shared-net
    driver: bridge
